python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Normal/1.bag /home/ebrenna8/NovemberDataCollection/Normal/1/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Normal/2.bag /home/ebrenna8/NovemberDataCollection/Normal/2/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Normal/3.bag /home/ebrenna8/NovemberDataCollection/Normal/3/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Normal/4.bag /home/ebrenna8/NovemberDataCollection/Normal/4/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Normal/5.bag /home/ebrenna8/NovemberDataCollection/Normal/5/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Normal/6.bag /home/ebrenna8/NovemberDataCollection/Normal/6/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Normal/7.bag /home/ebrenna8/NovemberDataCollection/Normal/7/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Normal/8.bag /home/ebrenna8/NovemberDataCollection/Normal/8/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Normal/9.bag /home/ebrenna8/NovemberDataCollection/Normal/9/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Normal/10.bag /home/ebrenna8/NovemberDataCollection/Normal/10/

python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Major/1.bag /home/ebrenna8/NovemberDataCollection/Major/1/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Major/2.bag /home/ebrenna8/NovemberDataCollection/Major/2/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Major/3.bag /home/ebrenna8/NovemberDataCollection/Major/3/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Major/4.bag /home/ebrenna8/NovemberDataCollection/Major/4/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Major/5.bag /home/ebrenna8/NovemberDataCollection/Major/5/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Major/6.bag /home/ebrenna8/NovemberDataCollection/Major/6/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Major/7.bag /home/ebrenna8/NovemberDataCollection/Major/7/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Major/8.bag /home/ebrenna8/NovemberDataCollection/Major/8/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Major/9.bag /home/ebrenna8/NovemberDataCollection/Major/9/
python parse_bag_file.py /home/ebrenna8/NovemberDataCollection/Major/10.bag /home/ebrenna8/NovemberDataCollection/Major/10/
